spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?serverTimezone=UTC
    driver: com.mysql.jdbc.Driver
    username: root
    password: pass@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8888